//post
export const BOARD_POST = "BOARD_POST";
export const BOARD_POST_SUCCESS = "BOARD_POST_SUCCESS";
export const BOARD_POST_FAILURE = "BOARD_POST_FAILURE";

//get list from DB
export const BOARD_LIST = "BOARD_LIST";
export const BOARD_LIST_SUCCESS = "BOARD_LIST_SUCCESS";
export const BOARD_LIST_FAILURE = "BOARD_LIST_FAILURE";

//get Entire list from DB
export const BOARD_ENTIRELIST = "BOARD_ENTIRELIST";
export const BOARD_ENTIRELIST_SUCCESS = "BOARD_ENTIRELIST_SUCCESS";
export const BOARD_ENTIRELIST_FAILURE = "BOARD_ENTIRELIST_FAILURE";

//get placeList from DB
export const BOARD_PLACELIST = "BOARD_PLACELIST";
export const BOARD_PLACELIST_SUCCESS = "BOARD_PLACELIST_SUCCESS";
export const BOARD_PLACELIST_FAILURE = "BOARD_PLACELIST_FAILURE";

//edit
export const BOARD_EDIT = "BOARD_EDIT";
export const BOARD_EDIT_SUCCESS = "BOARD_EDIT_SUCCESS";
export const BOARD_EDIT_FAILURE = "BOARD_EDIT_FAILURE";

//delete
export const BOARD_REMOVE = "BOARD_REMOVE";
export const BOARD_REMOVE_SUCCESS = "BOARD_REMOVE_SUCCESS";
export const BOARD_REMOVE_FAILURE = "BOARD_REMOVE_FAILURE";